In [1]:
import duckdb as ddb
import pandas as pd

In [2]:
sql_query = '''
show tables; 
'''

with ddb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2                     first_model
3         parking_violation_codes
4         parking_violations_2025
5                       ref_model
6  silver_parking_violation_codes
7       silver_parking_violations
8        silver_violation_tickets
9       silver_violation_vehicles

In [ ]:
sql_query_import_1 = """
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT * 
FROM read_csv_auto(
    'data/DOF_Parking_Violation_Codes_20260603.csv',
    normalize_names=True
)
"""

In [ ]:
sql_query_import_2 = """
CREATE OR REPLACE TABLE parking_violations_2025 AS
SELECT * 
FROM read_csv_auto(
    'data/sample_parking_violations_2025.csv',
    normalize_names=True
)
"""

In [ ]:
with ddb.connect("data/nyc_parking_violations.db") as con:
    con.sql(sql_query_import_1)
    con.sql(sql_query_import_2)

In [ ]:
sql_query = """
SELECT * FROM parking_violation_codes
LIMIT 5;
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

In [ ]:
sql_query = """
show tables; 
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

In [ ]:
sql_query = """
SELECT * FROM ref_model;
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

In [ ]:
sql_query = """
SELECT * FROM bronze_parking_violation_codes
LIMIT 3;
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

In [ ]:
sql_query = """
SELECT * FROM bronze_parking_violations
LIMIT 3;
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

In [5]:
sql_query = """
SELECT * FROM silver_violation_tickets
LIMIT 3; 
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

,summons_number,issue_date,violation_code,is_manhattan_96th_st_below,issuing_agency,violation_location,issuer_precinct,issuer_code,issuer_command,issuer_squad,violation_time,violation_county,violation_legal_code,fee_usd
0,4906674367,2024-07-08,36.0,False,V,NaN,0.0,0.0,None,None,0416A,QN,True,NaN
1,4906075502,2024-07-09,36.0,False,V,NaN,0.0,0.0,None,None,0424P,BX,True,NaN
2,4907839261,2024-07-17,36.0,False,V,NaN,0.0,0.0,None,None,0625P,BX,True,NaN